#---
## Zookeeper Service
#apiVersion: v1
#kind: Service
#metadata:
#  name: zookeeper-service
#spec:
#  ports:
#    - port: 2181
#      targetPort: 2181
#  selector:
#    app: zookeeper
#---
## Zookeeper StatefulSet
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: zookeeper
#spec:
#  serviceName: zookeeper-service
#  replicas: 1
#  selector:
#    matchLabels:
#      app: zookeeper
#  template:
#    metadata:
#      labels:
#        app: zookeeper
#    spec:
#      containers:
#        - name: zookeeper
#          image: confluentinc/cp-zookeeper:7.0.0
#          ports:
#            - containerPort: 2181
#          env:
#            - name: ZOOKEEPER_CLIENT_PORT
#              value: "2181"
#          volumeMounts:
#            - name: zookeeper-data
#              mountPath: /var/lib/zookeeper/data
#      volumes:
#        - name: zookeeper-data
#          emptyDir: {}
#---
## Kafka ConfigMap
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: kafka-config
#data:
#  server.properties: |
#    broker.id=${BROKER_ID}
#    listeners=PLAINTEXT://:9092
#    advertised.listeners=PLAINTEXT://${POD_NAME}.kafka-service.default.svc.cluster.local:9092
#    log.dirs=/var/lib/kafka/data
#    num.partitions=3
#    default.replication.factor=3
#    min.insync.replicas=2
#    zookeeper.connect=zookeeper-service:2181
#---
## Kafka Service
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#spec:
#  clusterIP: None
#  ports:
#    - port: 9092
#      targetPort: 9092
#  selector:
#    app: kafka
#---
## Kafka StatefulSet (No PVC/PV)
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: kafka
#spec:
#  serviceName: kafka-service
#  replicas: 3
#  selector:
#    matchLabels:
#      app: kafka
#  template:
#    metadata:
#      labels:
#        app: kafka
#    spec:
#      containers:
#        - name: kafka
#          image: confluentinc/cp-kafka:7.0.0
#          env:
#            - name: BROKER_ID
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#          ports:
#            - containerPort: 9092
#          volumeMounts:
#            - name: kafka-data
#              mountPath: /var/lib/kafka/data
#            - name: kafka-config
#              mountPath: /etc/kafka
#      volumes:
#        - name: kafka-data
#          emptyDir: {}
#        - name: kafka-config
#          configMap:
#            name: kafka-config